# Generated by Django 5.2.7 on 2025-10-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('image', models.ImageField(blank=True, null=True, upload_to='photos3 %Y %m %d', verbose_name='صورة الملف الشخصي')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية الوطنية')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CustomerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clint.customer')),
            ],
        ),
        migrations.AddField(
            model_name='customer',
            name='my_books',
            field=models.ManyToManyField(blank=True, related_name='customers', through='clint.CustomerBook', to='my_books.book', verbose_name='كتبي'),
        ),
        migrations.AddConstraint(
            model_name='customerbook',
            constraint=models.UniqueConstraint(fields=('customer', 'book'), name='unique_customer_book'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['name'], name='clint_custo_name_0b470e_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['email'], name='clint_custo_email_8d1985_idx'),
        ),
        migrations.AddIndex(
            model_name='customer',
            index=models.Index(fields=['phone'], name='clint_custo_phone_6224f9_idx'),
        ),
    ]
