# Generated by Django 5.2.7 on 2025-10-22 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='الاسم الكامل')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='البريد الإلكتروني')),
                ('phone', models.CharField(max_length=15, verbose_name='رقم الهاتف')),
                ('address', models.TextField(verbose_name='العنوان')),
                ('national_id', models.CharField(max_length=20, unique=True, verbose_name='رقم الهوية الوطنية')),
                ('date_of_birth', models.DateField(blank=True, null=True, verbose_name='تاريخ الميلاد')),
                ('occupation', models.CharField(blank=True, max_length=100, null=True, verbose_name='المهنة')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ التسجيل')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='تاريخ التحديث')),
            ],
            options={
                'verbose_name': 'عميل',
                'verbose_name_plural': 'العملاء',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['name'], name='clint_custo_name_0b470e_idx'), models.Index(fields=['email'], name='clint_custo_email_8d1985_idx'), models.Index(fields=['phone'], name='clint_custo_phone_6224f9_idx')],
            },
        ),
    ]
