# Generated by Django 5.2.7 on 2025-10-29 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0001_initial'),
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='my_books',
            field=models.ManyToManyField(blank=True, limit_choices_to={'status': 'sold'}, related_name='customers', through='clint.CustomerBook', to='my_books.book', verbose_name='كتبي المباعة'),
        ),
    ]
