# Generated by Django 5.2.7 on 2025-10-28 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='photos3 %Y %m %d', verbose_name='صورة الملف الشخصي'),
        ),
    ]
