# Generated by Django 5.2.7 on 2025-10-30 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0002_alter_customer_my_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='app_name',
            field=models.CharField(default=1, max_length=100, verbose_name='الاسم الكامل'),
            preserve_default=False,
        ),
    ]
