# Generated by Django 5.2.7 on 2025-10-28 20:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0002_customer_image'),
        ('my_books', '0009_alter_book_price_alter_book_retal_price_day_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='my_books',
            field=models.ManyToManyField(blank=True, to='my_books.book'),
        ),
    ]
