# Generated by Django 5.2.7 on 2025-11-06 05:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0003_customer_app_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customer',
            name='app_name',
        ),
        migrations.AddField(
            model_name='customer',
            name='user_id',
            field=models.CharField(default=1, max_length=10),
        ),
    ]
