# Generated by Django 5.2.7 on 2025-10-28 22:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0003_customer_my_books'),
        ('my_books', '0010_rename_catigory_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_date', models.DateTimeField(auto_now_add=True)),
                ('purchase_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_books.book')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clint.customer')),
            ],
        ),
        migrations.AlterField(
            model_name='customer',
            name='my_books',
            field=models.ManyToManyField(blank=True, related_name='customers', through='clint.CustomerBook', to='my_books.book', verbose_name='كتبي'),
        ),
        migrations.AddConstraint(
            model_name='customerbook',
            constraint=models.UniqueConstraint(fields=('customer', 'book'), name='unique_customer_book'),
        ),
    ]
