# Generated by Django 5.2.7 on 2025-11-06 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0004_remove_customer_app_name_customer_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='user_id',
            field=models.CharField(default=0, max_length=10),
        ),
    ]
