# Generated by Django 5.2.7 on 2025-11-09 18:02

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0005_alter_customer_user_id'),
        ('my_books', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRentedBook',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rental_start_date', models.DateTimeField(auto_now_add=True)),
                ('rental_end_date', models.DateTimeField(blank=True, null=True)),
                ('rental_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
            ],
            options={
                'verbose_name': 'كتاب مستأجر',
                'verbose_name_plural': 'الكتب المستأجرة',
            },
        ),
        migrations.AlterModelOptions(
            name='customerbook',
            options={'verbose_name': 'كتاب مملوك', 'verbose_name_plural': 'الكتب المملوكة'},
        ),
        migrations.RemoveConstraint(
            model_name='customerbook',
            name='unique_customer_book',
        ),
        migrations.RemoveField(
            model_name='customer',
            name='user_id',
        ),
        migrations.AddField(
            model_name='customer',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='customers/%Y/%m/%d', verbose_name='صورة الملف الشخصي'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='my_books',
            field=models.ManyToManyField(blank=True, related_name='owned_by_customers', through='clint.CustomerBook', to='my_books.book', verbose_name='كتبي المملوكة'),
        ),
        migrations.AddConstraint(
            model_name='customerbook',
            constraint=models.UniqueConstraint(fields=('customer', 'book'), name='unique_customer_purchased_book'),
        ),
        migrations.AddField(
            model_name='customerrentedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='my_books.book'),
        ),
        migrations.AddField(
            model_name='customerrentedbook',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clint.customer'),
        ),
        migrations.AddField(
            model_name='customer',
            name='my_rented_books',
            field=models.ManyToManyField(blank=True, related_name='rented_by_customers', through='clint.CustomerRentedBook', to='my_books.book', verbose_name='كتبي المستأجرة'),
        ),
        migrations.AddConstraint(
            model_name='customerrentedbook',
            constraint=models.UniqueConstraint(fields=('customer', 'book'), name='unique_customer_rented_book'),
        ),
    ]
