# Generated by Django 5.2.8 on 2025-12-02 21:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clint', '0006_customerrentedbook_alter_customerbook_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='customerrentedbook',
            name='unique_customer_rented_book',
        ),
        migrations.AddField(
            model_name='customerrentedbook',
            name='rental_status',
            field=models.CharField(choices=[('active', 'نشط'), ('returned', 'تمت الإعادة'), ('overdue', 'متأخر'), ('cancelled', 'ملغى')], default='active', max_length=10, verbose_name='حالة الإيجار'),
        ),
        migrations.AlterField(
            model_name='customer',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='المستخدم'),
            preserve_default=False,
        ),
    ]
