# Generated by Django 5.2.7 on 2025-10-28 22:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='photos %Y %m %d ')),
                ('auther_image', models.ImageField(blank=True, null=True, upload_to='photos2 %Y %m %d')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('status', models.CharField(choices=[('availble', 'availble'), ('rented', 'rented'), ('sold', 'sold'), ('avl_for_rent', 'avl_for_rent')], default='availble', max_length=100)),
                ('pages', models.IntegerField()),
                ('active', models.BooleanField(default=True)),
                ('retal_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('retal_proid', models.IntegerField(blank=True, null=True)),
                ('total_rental', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('discription', models.CharField(max_length=100)),
                ('catigery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_books.category')),
            ],
            options={
                'ordering': ['-id'],
            },
        ),
    ]
