# Generated by Django 4.2.20 on 2025-09-29 11:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catigory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('auther', models.CharField(max_length=100)),
                ('book_image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('auther_image', models.ImageField(blank=True, null=True, upload_to='photos')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('status', models.CharField(blank=True, choices=[('availble', 'availble'), ('rental', 'rental'), ('solid', 'solid')], max_length=100, null=True)),
                ('pages', models.IntegerField(blank=True, null=True)),
                ('active', models.BooleanField(default=True)),
                ('retal_price_day', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('retal_proid', models.IntegerField(blank=True, null=True)),
                ('catigery', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='my_books.catigory')),
            ],
        ),
    ]
