# Generated by Django 5.2.8 on 2025-12-02 21:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='total_rental',
        ),
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.TextField(),
        ),
    ]
