# Generated by Django 4.2.20 on 2025-09-29 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='auther_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos2 %Y %m %d'),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_image',
            field=models.ImageField(blank=True, null=True, upload_to='photos %Y %m %d '),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(default=0),
        ),
    ]
