# Generated by Django 4.2.20 on 2025-10-04 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0002_alter_book_auther_image_alter_book_book_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='rental_proid',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
    ]
