# Generated by Django 4.2.20 on 2025-10-05 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0003_book_rental_proid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='rental_proid',
            new_name='total_rental',
        ),
    ]
