# Generated by Django 5.2.7 on 2025-10-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0004_rename_rental_proid_book_total_rental'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='book',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='catigory',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='book',
            name='discription',
            field=models.CharField(blank=True, choices=[('availble', 'availble'), ('rental', 'rental'), ('sold', 'sold')], max_length=100, null=True),
        ),
    ]
