# Generated by Django 5.2.7 on 2025-10-15 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0005_alter_book_options_alter_catigory_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
