# Generated by Django 5.2.7 on 2025-10-16 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0006_alter_book_discription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='discription',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.IntegerField(),
        ),
    ]
