# Generated by Django 5.2.7 on 2025-10-18 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0007_alter_book_discription_alter_book_pages'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='status',
            field=models.CharField(choices=[('availble', 'availble'), ('rented', 'rented'), ('sold', 'sold'), ('avl_for_rent', 'avl_for_rent')], default='availble', max_length=100),
        ),
    ]
