# Generated by Django 5.2.7 on 2025-10-28 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_books', '0009_alter_book_price_alter_book_retal_price_day_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Catigory',
            new_name='Category',
        ),
    ]
